### ISSUE TITLE
Feature request: Export options

### ISSUE THREAD

**Issue by CMay** [SamiPerttu/FsMap3#1]
Great library and tool!  Thanks for all the work that went into it.  The roadmap looks nice, especially C# integration.  Unfortunately F# isn't supported in .NET Native yet :/

There are a couple of export options I would love to see.
- Right now the maximum export size is 8192x8192, but I'd like to be able to set an arbitrarily large size.
- Some form of transparency support would be exciting.
- It would be nice to have a button to reset the detail/zoom level to default since an export won't be seamless if "Tile All" is used unless it's at that default detail.

**Comment by SamiPerttu** [comment]
Thanks!
- I've been planning an export dialog for a while now. Probably in the next major version - I'll add it the roadmap as well. 
- Alpha (and likely depth, normal, etc.) support is coming with support for channels, i.e., a logical separation between source textures and whatever visual attributes they are assigned to.
- "Reset Zoom" in the context menu (press right mouse button in view) resets zoom.
