### ISSUE TITLE
Bug: Using context menu to create a custom preset causes crash

### ISSUE THREAD

**Issue by CMay** [SamiPerttu/FsMap3#2]
Selecting an existing preset from the dropdown lists asks if you want to overwrite that preset and works fine, however if you type in your own subsection and preset name FsMap just crashes.  Lost the first preset I wanted to save that way and had no luck recreating it, but File->SaveAs works fine, so I've been using that instead. :)

**Comment by SamiPerttu** [comment]
Yikes! That is horrible. The problem seems to be lack of writing permissions on the preset folder. I need to move the presets to a user directory. This is going to a bugfix release, I think. In the meantime, the crash will be prevented in the next commit.
